### ISSUE TITLE
Breaks if not .bowerc

### ISSUE THREAD

**Issue by carlitux** [Strider-CD/strider-bower#1]
The workflow is broken if not a valid .bowerc

**Comment by knownasilya** [comment]
Would totally take a PR for a check and an error message.

**Comment by carlitux** [comment]
@knownasilya my mistake... I didn't have installed bower and I assumed strider installed it.

**Comment by knownasilya** [comment]
It does use it's own, if you select **Use project's bower dependency** in the settings.

**Comment by carlitux** [comment]
@knownasilya yeah, I usually didn't put it on devDependencies... Thanks!
